language: python

python:
  - pypy3
  - pypy
  - 3.6
  - 3.5
  - 3.4
  - 2.7

# whitelist
# gh-pages is otherwise ignored by Travis CI
# Use a regex to whitelist gh-pages and all branches
branches:
  only:
    - gh-pages
    - /.*/

sudo: false

install:
  - travis_retry pip install pyflakes pep8

script:
    # Static analysis
  - pyflakes .
  - pep8 --statistics --count .

matrix:
  fast_finish: true
